> prettier --check ./**/*.ts --ignore-path .gitignore
Checking formatting...
[warn] server/api/controller/controller.ts
[warn] server/api/controller/index.ts
[warn] Code style issues found in 2 files. Forgot to run Prettier?
ERROR: lint:prettier exited with 1.
Error: Process completed with exit code 1.

> prettier --check ./**/*.tsx --ignore-path .gitignore

Checking formatting...
[warn] server/api/controller/controller.ts
[warn] server/api/controller/index.ts
[warn] Code style issues found in 2 files. Forgot to run Prettier?
ERROR: lint:prettier exited with 1.
Error: Process completed with exit code 1.

> prettier --check ./**/*.js --ignore-path .gitignore

Checking formatting...
[warn] server/api/controller/controller.ts
[warn] server/api/controller/index.ts
[warn] Code style issues found in 2 files. Forgot to run Prettier?
ERROR: lint:prettier exited with 1.
Error: Process completed with exit code 1.